import sys
import os

# --- PATH FIX ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
# ----------------

import streamlit as st
from frontend.components.sidebar import render_sidebar
from frontend.utils.api_client import request_ai_insights

# 1. Config Page
st.set_page_config(page_title="AI Insights", page_icon="🤖", layout="wide")

# 2. Load CSS
css_path = os.path.join(os.path.dirname(__file__), "..", "assets", "style.css")
try:
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
except FileNotFoundError:
    pass

# 3. Sidebar
render_sidebar()

# 4. Main Content
st.title("🤖 AI Strategic Consultant")
st.markdown("Get automated insights and budget allocation recommendations generated by **Gemini Pro**.")

# --- CHECK DATA ---
if "analysis_result" not in st.session_state:
    st.warning("⚠️ No data available for analysis.")
    st.info("Please upload a CSV file in the 'Upload Data' page first.")
    st.stop()

# Recuperamos el resumen que ya calculamos (sin necesidad de enviar el CSV de nuevo)
analysis_json = st.session_state["analysis_result"]
summary_data = analysis_json["summary"] # Lista de métricas por canal

col1, col2 = st.columns([1, 2])

with col1:
    st.info("The AI Agent will analyze your ROAS, CPA, and Conversion rates to suggest improvements.")
    
    # Botón Mágico
    if st.button("✨ Generate AI Report", type="primary"):
        # Guardamos el estado para que no se borre al recargar
        st.session_state["ai_report"] = None 
        
        # --- AQUÍ OCURRE LA MAGIA ---
        # El Frontend llama al Backend, y el Backend llama a Google
        insight_text = request_ai_insights(analysis_json)
        
        if insight_text:
            st.session_state["ai_report"] = insight_text

with col2:
    # Mostramos el reporte si existe
    if "ai_report" in st.session_state and st.session_state["ai_report"]:
        st.success("Analysis Generated Successfully!")
        st.divider()
        st.markdown(st.session_state["ai_report"])
        
    elif "ai_report" not in st.session_state:
        st.markdown("""
        ### Waiting for request...
        
        Click the button to start the agent.
        """)