import requests
import streamlit as st
import pandas as pd
from typing import Optional, Dict, Any

# In production, this URL should come from os.getenv()
API_BASE_URL = "http://127.0.0.1:8000"

def get_health_check() -> Optional[Dict[str, Any]]:
    """Checks if Backend is healthy"""
    try:
        response = requests.get(f"{API_BASE_URL}/", timeout=2)
        if response.status_code == 200:
            return response.json()
        return None
    except requests.exceptions.ConnectionError:
        return None
    except Exception as e:
        st.error(f"Unexpected error: {e}")
        return None

def send_csv_to_backend(file) -> Optional[Dict[str, Any]]:
    """Uploads CSV to Backend Analysis Engine"""
    try:
        files = {"file": (file.name, file, "text/csv")}
        with st.spinner("⏳ Sending data to Analytics Engine..."):
            response = requests.post(f"{API_BASE_URL}/analytics/upload-csv", files=files)
        
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 400:
            st.error(f"⚠️ Validation Error: {response.json().get('detail')}")
            return None
        else:
            st.error(f"❌ Server Error ({response.status_code}): {response.text}")
            return None
    except Exception as e:
        st.error(f"Error processing file: {str(e)}")
        return None

# --- MISSING FUNCTION (Esta es la que faltaba) ---
def request_ai_insights(summary_data: Dict[str, Any]) -> Optional[str]:
    """
    Sends the metrics summary to the Backend AI Agent.
    Returns the markdown text generated by Gemini.
    """
    try:
        # Preparamos el payload (cuerpo del mensaje)
        payload = {"summary_data": summary_data}
        
        with st.spinner("🤖 AI Agent is thinking... (This may take a few seconds)"):
            # Llamamos al endpoint que creamos en recommendations.py
            response = requests.post(f"{API_BASE_URL}/ai/generate-insights", json=payload)
            
        if response.status_code == 200:
            return response.json().get("response")
        else:
            st.error(f"AI Error ({response.status_code}): {response.text}")
            return None
            
    except requests.exceptions.ConnectionError:
        st.error("🚨 Cannot connect to AI Agent. Is the backend running?")
        return None
    except Exception as e:
        st.error(f"Unexpected error: {str(e)}")
        return None